version: '3'

services:
  minio:
    image: tobi312/minio:latest
    #image: minio/minio
    ports:
      - "8000:9000"
      - "9001:9001"
    volumes:
      - ${DATA_DIR}:/data
      - ./certs:/certs
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
    #command: server --console-address ":9001" /data
    command: server -S /certs --console-address ":9001" /data
    restart: always
    # to generate certs: openssl req -new -x509 -nodes -days 730 -keyout ./certs/private.key -out ./certs/public.crt -config openssl.conf

  sshtunnel:
    image: jnovack/autossh:latest
    container_name: remote-nodeexporter
    environment:
      - SSH_REMOTE_HOST=docker01.letsmakeit.dk
      - SSH_BIND_IP=\*
      - SSH_TUNNEL_PORT=443
      #- SSH_TARGET_PORT=9001
      - SSH_TARGET_PORT=8000
      - SSH_TARGET_HOST=172.17.0.1
      #- SSH_TARGET_HOST=host.docker.internal
      - SSH_MODE=-N -R
    restart: always
    volumes:
      - ./sshkey/autossh_id_rsa:/id_rsa
    #extra_hosts:
    #  - host.docker.internal:127.0.0.1
    #links:
    #  - "sshtunnel:minio"
    #ports:
    #  - "443:443"

