version: '3'
networks:
  net1:
    driver: 'bridge'
services:
  minio:
    image: tobi312/minio:latest
    #image: minio/minio
    #ports:
    #  - "8000:9000"
    #  - "9001:9001"
    volumes:
      - ${DATA_DIR}:/data
      - ./certs:/certs
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    #command: server --console-address ":9001" /data
    command: server --console-address ":7000" /data
    restart: always
    networks:
      - net1

    # to generate certs: openssl req -new -x509 -nodes -days 730 -keyout ./certs/private.key -out ./certs/public.crt -config openssl.conf

  sshtunnel:
    image: jnovack/autossh:latest
    environment:
      - SSH_REMOTE_HOST=docker01.letsmakeit.dk
      - SSH_BIND_IP=\*
      - SSH_TUNNEL_PORT=8000
      #- SSH_TARGET_PORT=9001
      - SSH_TARGET_PORT=9000
      - SSH_TARGET_HOST=minio
      #- SSH_TARGET_HOST=172.17.0.1
      #- SSH_TARGET_HOST=host.docker.internal
      - SSH_MODE=-R
      #- SSH_OPTIONS=-N -R \*:7000:minio:9001
    restart: always
    volumes:
      - ./sshkey/autossh_id_rsa:/id_rsa
    networks:
      - net1
  sshtunneladmin:
    image: jnovack/autossh:latest
    environment:
      - SSH_REMOTE_HOST=docker01.letsmakeit.dk
      - SSH_BIND_IP=\*
      - SSH_TUNNEL_PORT=7000
      #- SSH_TARGET_PORT=9001
      - SSH_TARGET_PORT=7000
      - SSH_TARGET_HOST=minio
#      #- SSH_TARGET_HOST=host.docker.internal
      - SSH_MODE=-N -R
    restart: always
    volumes:
      - ./sshkey/autossh_id_rsa:/id_rsa
    networks:
      - net1
