version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "8001:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
      - ./certs:/certs
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
    command: server --console-address ":9001" /data
    #command: server -S /certs --console-address ":9001" /data
    # to generate certs: openssl req -new -x509 -nodes -days 730 -keyout ./certs/private.key -out ./certs/public.crt -config openssl.conf
